/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static Integer addsUp(Integer int1, Integer int2) {
        return int1+int2;
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
